### PR TITLE
Added Build Script for Windows

### PR DESCRIPTION
**Pull request by RaedAddala**
## Done:

- Added Build Script for Windows that generates executables for all optimisation levels
- Added 2 Scripts for verifying software: A short one that gives Warnings and A long one that uses clang Static Analysis 
- Scripts could be configured

## Future Tasks:

- [ ] Improve Tests: tests must be way bigger for the performance difference to be apparent
- [ ] Make the Program accept two parameters: 1- the string to search for and 2- the text file to search in
- [ ] Add other Algorithms to test.

### CODE REVIEW

**Comment by zhenrong-wang** [comment]
PR received. Reviewing it now.

**Comment by zhenrong-wang** [comment]
For stricter test, I already have a random string generator and a random substring extractor.

Will add them to this repo, plan:

1. Generate random strings with length from 2 to 65536, or even longer.

2. Extract corresponding substrings.

3. Test these different approaches seperately.

Unfortunately my laptop is in repair and I cannot code now.

**Comment by RaedAddala** [comment]
I was thinking about searching for a substring in a long text for the tests.

In the tests, we are using short strings, the problem with it is that performance differences can't be apparent. Computers are fast enough that they will not make a huge difference in relatively small strings. 

Also, I was thinking about trying to benchmark using best Case Scenario (find the substring quickly ), Worst Cast Scenario (the string isn't there) and many other random very long texts.

**Comment by zhenrong-wang** [comment]
I added and tested the random string and random_substring generator to the repository. Please take a look.

**Comment by zhenrong-wang** [comment]
It seems that for random string testing, CPP string.find is much quicker. I was wrong.

Please check the latest code.

**Comment by RaedAddala** [comment]
I will check it out over the weekend.
I suspect string.find uses parallelism or SIMD. If they are using the Naive Approach, if the substring isn't too big, it will be of the complexity of O(n) with n the size of the string we are searching in. The threshold for implementing KMP may be bigger than what we already have.
This needs its own analysis.

**Comment by zhenrong-wang** [comment]
> I will check it out over the weekend.
> I suspect string.find uses parallelism or SIMD. If they are using the Naive Approach, if the substring isn't too big, it will be of the complexity of O(n) with n the size of the string we are searching in. The threshold for implementing KMP may be bigger than what we already have.
> This needs its own analysis. 

I am not quite familiar, but is there any way to make the C approaches use SIMD? Needs special compiling options or needs to rewrite the codes?

Another point is, totally random string tests may be meaningless because in practice, we usually face meaningful strings.

**Comment by RaedAddala** [comment]
SIMD can be used in C/C++ and they are called intrinsics. These are instructions that are platform dependant and because C/C++ aims for portability and its premise is that you can compile your code on whatever platform, these parts didn't get to the standard. However, Compilers such as GNU GCC and Clang have builtins that you can use depending on your target platform.

Check these links for further information:

- http://const.me/articles/simd/simd.pdf
- https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html : here is an example using gnu gcc

**Pull request merged**
